language: node_js
node_js:
- lts/*
cache:
  yarn: true
  directories:
  - node_modules
sudo: required
addons:
  chrome: stable
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
script:
- npm --version
- npm install
- npm test
- npm run package
after_success:
- npm run test:codecov-upload
- npm run test:coveralls-upload
before_deploy:
- cd dist/govuk-formly-templates
deploy:
  provider: npm
  email: jenkins-reform@hmcts.net
  api_key:
    secure: oXhvXHPHfdeTn7e01WVFY6nkAyKD3Z+g2xs5hmJCEUg+OSDZDvTelwIXyp4XOky7TVbXldqiI+zcgcoD+gWB4+5nSjxyxD98qptf4qwg2Me5f7RhisvHlPSZI1mzPo9cuaAS0XwERmpjG2aOOSBZUWLAM5i3LBv3sdYfW3fpqFlVvTWyyqdfmq55xcwfIdwq7K2Fq/2aPjFdLYCR0VUAi09WHJUWB8EguDnbYQHg5cJJnJ1cOV+Dt+molHbgF+YdeVAqUTlyeD8Y1OZXqUyoniFJ6q39qXlvwPkYLURjEM2v0n8q0VshKvifLST7Em+D60Gy2pPlHCGXZd/vk+qZKchdOaTEq51JembKpNsarX32GmUltb01zgWpdUBUunUqD4lR3X0/G3WKX+N+UqxpcGf2caRpDlDeWUNHabKVPjzbTvab6Y/MI7pquWaBAelSOOeTp48wqKnNOGZAsJvztfzcscXjlMzAXXKtI5WS2lRFLm85hxfRk2uhRdW5J9I/M1iVgAkeOcWNCVU+vfvXrKcX6YD1PhkRjgSMnRP3bepStWG3vZFjQgnb+3bMFrUXOckCSj7ndw53wj1hB2DcxrR3zc11rqYguOiMuD2toIw5LitbOoGVW2CspkjanQ6GFZCHnLAFo43VdHRKoI8cDPK9PqKB3l716gh6WUZX9MM=
  skip_cleanup: true
  on:
    tags: true
    repo: hmcts/govuk-formly-templates
    all_branches: true
